name: Bump formulae on schedule or request

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.ya?ml'
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every day at 5am
    - cron: "0 5 * * *"

env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
  FORMULAE: >
    abcmidi
    ack
    activemq
    alda
    aliddns
    aliyun-cli
    allure
    alluxio
    ammonite-repl
    angular-cli
    ansible-lint
    ant
    ant@1.9
    anycable-go
    apache-archiva
    apache-drill
    apache-flink
    apache-geode
    apache-opennlp
    apache-spark
    apidoc
    apktool
    apt
    aptos
    arb
    argo
    argocd
    argocd-autopilot
    argocd-vault-plugin
    arkade
    armadillo
    arrayfire
    arturo
    asciidoctorj
    ask-cli
    assh
    asuka
    asymptote
    atlantis
    atuin
    autorest
    autorestic
    avrdude
    aws-cdk
    aws-elasticbeanstalk
    aws-es-proxy
    aws-rotate-key
    aws-sam-cli
    azcopy
    b3sum
    bagit
    baidupcs-go
    ballerina
    bash_unit
    batik
    bazel
    bazelisk
    bbtools
    bcoin
    bear
    benthos
    berglas
    bettercap
    bigloo
    binaryen
    bnd
    bosh-cli
    bottom
    brev
    brew-php-switcher
    brook
    broot
    bubblewrap
    buildifier
    buildkit
    buildozer
    buildpulse-test-reporter
    buku
    bundletool
    bupstash
    butane
    byacc
    byteman
    bzt
    caddy
    cadence
    cadence-workflow
    caire
    calicoctl
    cargo-audit
    cargo-bloat
    cargo-c
    cargo-edit
    cargo-instruments
    cargo-llvm-lines
    cargo-outdated
    cargo-watch
    carrot2
    cassandra
    cassandra-reaper
    catch2
    cdk8s
    certigo
    cfr-decompiler
    cfssl
    cgl
    chamber
    charmcraft
    cheat
    checkstyle
    chezmoi
    choose-rust
    chromaprint
    chronograf
    cilium-cli
    circleci
    clair
    clamav
    clarinet
    clash
    clazy
    cliclick
    clojurescript
    closure-compiler
    cloud-nuke
    cloudflare-wrangler
    cloudformation-guard
    clusterctl
    cobalt
    code-minimap
    cointop
    coinutils
    colima
    composer
    condure
    conftest
    consul
    consul-template
    contentful-cli
    convox
    copilot
    coredns
    cortex
    cosign
    couchdb
    croc
    cromwell
    crowdin
    crun
    css-crush
    csvq
    csvtk
    cubejs-cli
    cweb
    cypher-shell
    cyrus-sasl
    dafny
    darkstat
    datree
    dbdeployer
    ddrescue
    deark
    delve
    deno
    dependency-check
    derby
    detekt
    detox
    devspace
    dex2jar
    diamond
    diesel
    diffoscope
    difftastic
    digdag
    django-completion
    djl-serving
    dnscontrol
    dnscrypt-proxy
    dnsx
    docker
    docker-compose
    docker-credential-helper
    docker-slim
    docker-squash
    doctl
    docuum
    dolt
    dosbox-staging
    dotenv-linter
    double-conversion
    doxygen
    dprint
    driftctl
    drill
    drone-cli
    druid
    dstask
    dua-cli
    duckscript
    dune
    dust
    dvc
    dynare
    easyengine
    efm-langserver
    ehco
    eksctl
    elan-init
    elfutils
    elixir
    embulk
    emscripten
    envconsul
    envoy
    esbuild
    eslint
    esptool
    etcd
    ethereum
    exploitdb
    faas-cli
    fabric-installer
    fantom
    faudio
    fblog
    fdroidserver
    feh
    fennel
    feroxbuster
    ffsend
    findomain
    firebase-cli
    firefoxpwa
    flac
    flank
    flarectl
    fleet-cli
    flow-cli
    fluent-bit
    flume
    flyway
    fmt
    fn
    fontforge
    fop
    ford
    fortio
    frugal
    fselect
    func-e
    fuse-overlayfs
    fuseki
    futhark
    gatsby-cli
    gau
    gdu
    geeqie
    geph4
    gerbil-scheme
    gh
    ghz
    ghz-web
    gifski
    ginac
    git-annex
    git-cliff
    git-delta
    git-lfs
    git-town
    gitbackup
    gitbucket
    gitlab-runner
    gitleaks
    gitql
    glassfish
    gleam
    global
    glooctl
    gmailctl
    gmic
    gmsh
    gnunet
    gnupg-pkcs11-scd
    gnuplot
    go-md2man
    gofumpt
    gojq
    golang-migrate
    golangci-lint
    google-java-format
    goose
    gopass
    gopls
    gor
    goredo
    goreleaser
    goreman
    gosec
    gostatic
    govc
    gowsdl
    gpg-tui
    gradle
    gradle-completion
    gradle-profiler
    grafana
    grails
    grin
    gromacs
    groovy
    groovysdk
    gsmartcontrol
    gsoap
    gupnp-tools
    hadoop
    halide
    hapi-fhir-cli
    hasura-cli
    hcloud
    helm
    helmfile
    helmsman
    hexyl
    hidapi
    himalaya
    hive
    hivemind
    hledger
    hpack
    htmldoc
    htmlq
    htmltest
    htpdate
    httpx
    hyperfine
    iamy
    igv
    imagemagick
    imagemagick@6
    imap-backup
    imapsync
    imgproxy
    influxdb
    influxdb-cli
    influxdb@1
    ioctl
    ipinfo-cli
    ipmiutil
    ipopt
    ircd-hybrid
    istioctl
    ivy
    jadx
    java-service-wrapper
    jena
    jenkins
    jenkins-job-builder
    jenkins-lts
    jetty
    jfrog-cli
    jhipster
    jmeter
    jnethack
    jql
    jrnl
    jruby
    jsonnet
    jsvc
    juju
    just
    k2tf
    k3d
    k3sup
    k6
    k9s
    kafka
    kahip
    kalker
    kamel
    kapacitor
    kcat
    kcptun
    keptn
    kepubify
    keydb
    ki
    kickstart
    kind
    kitchen-sync
    kn
    knot
    knot-resolver
    ko
    kompose
    kops
    kotlin
    krew
    ktlint
    kube-linter
    kubeaudit
    kubebuilder
    kubecfg
    kubecm
    kubeconform
    kubergrunt
    kubernetes-cli
    kubeseal
    kubespy
    kubevela
    kubie
    kumactl
    kustomize
    kyma-cli
    kyverno
    languagetool
    latex2html
    latexml
    lazydocker
    ld-find-code-refs
    lean-cli
    lefthook
    lego
    leiningen
    lexbor
    lf
    libdap
    libepoxy
    libgetdata
    libgr
    liblinear
    libnfs
    liboqs
    libpano
    libpipeline
    librdkafka
    librespot
    libsndfile
    lima
    linkerd
    linode-cli
    liquibase
    lmod
    localstack
    log4cxx
    lout
    luau
    lux
    lychee
    macchina
    mage
    mailutils
    mapcidr
    marked
    marp-cli
    matterbridge
    maven
    mavsdk
    maxwell
    mdbook
    mdcat
    mdzk
    meilisearch
    melody
    memcached
    mesa
    meson
    metabase
    micro
    micronaut
    mill
    mimirtool
    minetest
    minikube
    miniserve
    mitmproxy
    mmark
    mmctl
    moar
    mockery
    mockserver
    moco
    molecule
    mongocli
    mongodb-atlas-cli
    monolith
    moto
    mpv
    muffet
    murex
    mutt
    mydumper
    mypy
    naabu
    nagios
    nanoflann
    nativefier
    nats-server
    nats-streaming-server
    naturaldocs
    navi
    ncspot
    needle
    neo4j
    neofetch
    neomutt
    nerdctl
    nest
    netdata
    nethogs
    netlify-cli
    newrelic-cli
    newrelic-infra-agent
    nfpm
    nng
    node_exporter
    node-sass
    nomad
    notcurses
    nsq
    nuclei
    numcpp
    nushell
    oauth2_proxy
    ocaml-findlib
    oci-cli
    ocp
    ocrmypdf
    octave
    oha
    okteto
    omniorb
    onednn
    onedrive
    ooniprobe
    opa
    openrtsp
    openiothub-server
    opensearch
    operator-sdk
    or-tools
    oras
    orc-tools
    orientdb
    orocos-kdl
    ortp
    osm
    ott
    oxipng
    pacapt
    packer
    passenger
    patchelf
    payara
    pdftk-java
    pdm
    pdnsrec
    pgbadger
    pgbouncer
    pgloader
    pgweb
    phoronix-test-suite
    php-code-sniffer
    php-cs-fixer
    phpmd
    phpmyadmin
    phpstan
    pianod
    picard-tools
    pig
    pillow
    plantuml
    plow
    pmd
    pngquant
    pnpm
    podman
    postgis
    powerman
    pre-commit
    prestd
    prestodb
    principalmapper
    procs
    protoc-gen-go-grpc
    psalm
    pstoedit
    pueue
    pushpin
    pwntools
    py-spy
    pyflow
    pyoxidizer
    qjackctl
    qpid-proton
    questdb
    rancher-cli
    rav1e
    rbspy
    rbw
    rclone
    rcs
    rebar3
    recode
    regina-rexx
    regula
    reminiscence
    reposurgeon
    revive
    rhit
    riemann
    rke
    rollup
    rosa-cli
    rover
    rpg-cli
    rqlite
    rubberband
    rustup-init
    s-search
    s2n
    saml2aws
    sbt
    scala
    scorecard
    scotch
    scummvm
    scummvm-tools
    scw
    sdl2
    seaweedfs
    selene
    selenium-server
    seqkit
    ser2net
    serverless
    shadowenv
    sheldon
    shellharden
    shellz
    shfmt
    signal-cli
    silicon
    singularity
    sjk
    skaffold
    skopeo
    skylighting
    slackcat
    sleuthkit
    slides
    smimesign
    sn0int
    sniffer
    sniffglue
    solana
    sollya
    solr
    sonarqube
    sonobuoy
    sponge
    spotbugs
    spotify-tui
    sqlancer
    sqlc
    sqlmap
    sqlx-cli
    sshs
    sslyze
    stanford-corenlp
    starship
    staticcheck
    statix
    stdman
    stellar-core
    step
    storm
    streamlink
    stress-ng
    structurizr-cli
    stunnel
    stylish-haskell
    subfinder
    subversion
    suite-sparse
    sundials
    suricata
    svgbob
    svgo
    svtplay-dl
    swagger-codegen
    swagger-codegen@2
    swagger2markup-cli
    syncthing
    sysdig
    talisman
    tanka
    tcsh
    tctl
    tealdeer
    tectonic
    tektoncd-cli
    teku
    teleport
    tendermint
    tengo
    termshark
    terracognita
    terraform-inventory
    terraform-ls
    terraform-provider-libvirt
    terraform-rover
    terraformer
    terragrunt
    terrascan
    tfsec
    thanos
    thrift
    tika
    tile38
    timg
    tm
    toast
    tomcat
    tomcat-native
    tomcat@8
    tomcat@9
    tomee-plus
    tomee-webprofile
    topgrade
    traefik
    trafficserver
    tree-sitter
    triangle
    trivy
    trojan-go
    typedb
    tz
    uni
    universal-ctags
    v2ray
    vala
    valabind
    vale
    vapoursynth
    vault
    vault-cli
    veclibfort
    velero
    vercel-cli
    vgrep
    virgil
    virustotal-cli
    vite
    vitess
    vivid
    vnstat
    volta
    vpn-slice
    vsearch
    vsh
    vue-cli
    wabt
    wakatime-cli
    wallpaper
    wapm
    wartremover
    wasm-pack
    wasmer
    wasmtime
    watchexec
    waypoint
    webdis
    webp
    webpack
    websocat
    webtorrent-cli
    wgcf
    whistle
    whois
    wildfly-as
    wireguard-go
    wiremock-standalone
    wolfssl
    wxwidgets
    xcbeautify
    xclogparser
    xdpyinfo
    xerces-c
    xgboost
    xh
    xplr
    xray
    yaegi
    ykman
    yosys
    youtubedr
    yq
    z3
    zabbix
    zbctl
    zellij
    zenith
    znapzend
    zola
    zookeeper
    zoxide
    zstd
    zydis

permissions:
  contents: read

jobs:
  autobump:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump formulae
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CORE_REPO_WORKFLOW_TOKEN }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
