name: Manage long timeout labels

on:
  pull_request_target:
    types:
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  GH_REPO: ${{ github.repository }}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1
  PR: ${{ github.event.number }}

jobs:
  label:
    permissions:
      pull-requests: write # for `gh pr edit`
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'Homebrew' &&
      github.event.label.name == 'CI-long-timeout'
    steps:
      - name: Re-label PR
        run: gh pr edit "$PR" --add-label CI-long-timeout
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save pull request number
        run: |
          mkdir -p pr
          echo "$PR" > pr/number

      - uses: actions/upload-artifact@v3
        with:
          name: pull-number
          path: pr
